### ISSUE TITLE
npm run dev on localhost gives errors 

### ISSUE THREAD

**Issue by ApplyFrank** [KekOnTheWorld/kekontheworld.github.io#91]
Hello KekOnTheWorld, I'm fairly new to web dev and even newer to Svelte, I come from iOS development. 

I forked your repository -> **npm install** -> **npm run dev** and ran into this issue 
<img width="1483" alt="Screenshot 2023-06-21 at 3 36 20 PM" src="https://github.com/KekOnTheWorld/kekontheworld.github.io/assets/105822946/8736135d-4dd9-44ce-a281-813f6a0788fe">
So I removed the .js which now looks like this 

`import vertexShader from "$lib/shaders/halloween.vert";
   import fragmentShader from "$lib/shaders/halloween.frag";`

I then ran **npm run dev** but ran into these issues when I go to localhost:5173
<img width="1476" alt="Screenshot 2023-06-21 at 3 38 08 PM" src="https://github.com/KekOnTheWorld/kekontheworld.github.io/assets/105822946/20f8cece-1bf7-49a2-afe6-4070d1b1f321">
<img width="1491" alt="Screenshot 2023-06-21 at 3 38 20 PM" src="https://github.com/KekOnTheWorld/kekontheworld.github.io/assets/105822946/393a4aa8-eef3-49ea-ad78-f58700ea21c4">
<img width="1492" alt="Screenshot 2023-06-21 at 3 40 24 PM" src="https://github.com/KekOnTheWorld/kekontheworld.github.io/assets/105822946/11f005aa-a264-4d01-8b38-83e52be55e7c">

but if I do **npm run build** -> **npm run preview** I can see my changes being updated on localhost:4173/
Any thoughts and what am I doing wrong? And do I have to **npm run build** everytime I want to see my changes? 
Thank you,
Frank

**Comment by lbirkert** [comment]
> Hello KekOnTheWorld, I'm fairly new to web dev and even newer to Svelte, I come from iOS development.
> 
> I forked your repository -> **npm install** -> **npm run dev** and ran into this issue <img alt="Screenshot 2023-06-21 at 3 36 20 PM" width="1483" src="https://user-images.githubusercontent.com/105822946/247779618-8736135d-4dd9-44ce-a281-813f6a0788fe.png"> So I removed the .js which now looks like this
> 
> `import vertexShader from "$lib/shaders/halloween.vert"; import fragmentShader from "$lib/shaders/halloween.frag";`
> 
> I then ran **npm run dev** but ran into these issues when I go to localhost:5173 <img alt="Screenshot 2023-06-21 at 3 38 08 PM" width="1476" src="https://user-images.githubusercontent.com/105822946/247779953-20f8cece-1bf7-49a2-afe6-4070d1b1f321.png"> <img alt="Screenshot 2023-06-21 at 3 38 20 PM" width="1491" src="https://user-images.githubusercontent.com/105822946/247779990-393a4aa8-eef3-49ea-ad78-f58700ea21c4.png"> <img alt="Screenshot 2023-06-21 at 3 40 24 PM" width="1492" src="https://user-images.githubusercontent.com/105822946/247780010-11f005aa-a264-4d01-8b38-83e52be55e7c.png">
> 
> but if I do **npm run build** -> **npm run preview** I can see my changes being updated on localhost:4173/ Any thoughts and what am I doing wrong? And do I have to **npm run build** everytime I want to see my changes? Thank you, Frank

Hey, the first error is caused by a missing .js file which would be generated by running `src/lib/shaders/convert.js`. The second issue seams to be with the `svelte-ogl` dependency. I have not maintained this package for a while, which is why its dependencies probably had a few breaking changes.

I'll take a look at [svelte-ogl](https://github.com/GamePowerX/svelte-ogl) some time this week, but I should note that I am now officially deprecating this repository in favor of my [new website](https://lbirkert.com).

Take care

**Comment by ApplyFrank** [comment]
thank you for the pointers and thank you for your response !

**Comment by lbirkert** [comment]
Rolling back to the dependencies found in an older commit fixes the issue. #1c926f1e131082e70d20592f27242faa4d945769

If you want to try again just run `git pull` and  `npm i` to update the dependencies.
